"""Arm B — PipelineRL.

The GPUs are partitioned once and never change role:

    GPUs [0, N-k)   trainers   — always training
    GPUs [N-k, N)   inference  — always generating

A producer thread keeps the inference GPUs saturated and drops finished rollouts into a
queue. The main thread pulls batches off that queue and takes optimizer steps. After every
step it pushes the new weights into the LIVE engine — generation does not stop, the KV
cache is not dropped, and sequences already in flight simply continue under newer weights.

Two consequences the conventional arm does not have, both measured rather than assumed:

  * STALENESS. A sample was generated by weights that are now `lag` optimizer steps old.
    lag > 0 makes the data off-policy, which is why grpo.py's clipped importance ratio is
    load-bearing here and inert in the conventional arm. Samples staler than cfg.max_lag
    are dropped, and the drop rate is recorded — a high drop rate means the generator is
    outrunning the trainer and the split is mis-sized.

  * MIXED-POLICY SEQUENCES. A single sequence can be partly generated by old weights and
    partly by new ones. We record the lag at the moment the sequence FINISHED, which is a
    lower bound on its true staleness. This is an approximation and is stated as such in
    the write-up rather than hidden.

If the probe shows vLLM cannot accept weights mid-decode, set cfg.inflight_updates=False:
generation is then quiesced around the update (KV cache still retained, no re-prefill). That
is a strictly weaker claim and the telemetry records inflight=False so every figure and the
visualizer show which mode actually ran.
"""
from __future__ import annotations

import queue
import threading
import time

from .batching import rollouts_to_batch, vllm_output_to_rollouts
from .data import build_chat, load_task, reward_fn
from .engine import EngineWeightError, Generator, Trainer
from .telemetry import Telemetry


def run(cfg, tel: Telemetry) -> dict:
    from transformers import AutoTokenizer

    tok = AutoTokenizer.from_pretrained(cfg.model)
    problems = load_task(cfg.task, seed=cfg.seed)
    tel.phase("setup", n_problems=len(problems))

    infer_gpus = cfg.infer_gpu_ids
    train_gpus = cfg.train_gpu_ids
    tel.phase("partition", infer=infer_gpus, train=train_gpus)

    # Never sleeps: these GPUs belong to the generator for the whole run.
    gen = Generator(cfg, tel, gpu_ids=infer_gpus, sleepable=False)
    trainer = Trainer(cfg, tel, gpu_ids=train_gpus)

    # VERIFY the split is physically real. The whole PipelineRL claim is that generation and
    # training occupy DIFFERENT GPUs concurrently; if a CUDA_VISIBLE_DEVICES mix-up put them
    # on the same device, every downstream number would still look plausible while measuring
    # something else entirely. A GPU holding a vLLM engine has little free memory; an unused
    # one has nearly all of it. So the free-memory profile is a cheap physical witness.
    import torch as _torch

    free_gib = {g: round(_torch.cuda.mem_get_info(g)[0] / 2**30, 2)
                for g in range(cfg.n_gpus)}
    trainer_idx = trainer.dev.index
    trainer_alloc = _torch.cuda.memory_allocated(trainer.dev) / 2**30
    tel.emit("placement", trainer_dev=str(trainer.dev), infer=infer_gpus,
             train=train_gpus, free_gib=free_gib,
             trainer_alloc_gib=round(trainer_alloc, 2))
    print(f"[pipeline] placement — trainer={trainer.dev} (alloc {trainer_alloc:.2f} GiB) "
          f"infer={infer_gpus} free GiB/GPU={free_gib}", flush=True)

    # Two independent conditions, both necessary:
    #   1. the trainer must not sit on an inference GPU (the CVD-leak failure mode), and
    #   2. every inference GPU must actually hold an engine.
    #
    # Do NOT test "is the trainer's GPU mostly free" — a 0.5B model in bf16 is ~1 GiB on a
    # 22 GiB card, so 95% free is entirely normal. An earlier version of this guard used
    # that test and cried wolf on a correctly-placed run.
    if trainer_idx in infer_gpus:
        raise RuntimeError(
            f"trainer is on cuda:{trainer_idx}, which is an INFERENCE gpu ({infer_gpus}). "
            f"The train/infer split did not happen — almost certainly a "
            f"CUDA_VISIBLE_DEVICES leak. Refusing to run: the result would look valid and "
            f"mean nothing.")
    total_gib = _torch.cuda.get_device_properties(0).total_memory / 2**30
    vacant = [g for g in infer_gpus if free_gib[g] > 0.75 * total_gib]
    if vacant:
        raise RuntimeError(
            f"inference GPU(s) {vacant} hold no engine (free GiB: {free_gib}). "
            f"Generation would not be running where the telemetry claims it is.")
    if trainer_alloc < 0.05:
        raise RuntimeError(
            f"trainer allocated only {trainer_alloc:.3f} GiB on {trainer.dev} — the model "
            f"does not appear to be resident there.")

    # Engines are up. Everything before this point is one-off setup (model load,
    # torch.compile, CUDA-graph capture) during which the GPUs are legitimately not
    # doing RL work. Counting it as "idle" made gpu_busy_frac read 8% on a smoke run
    # and would have buried the real bubble under startup cost.
    tel.phase("ready")

    rollout_q: queue.Queue = queue.Queue(maxsize=cfg.prompts_per_step * 4)
    stop = threading.Event()
    weight_version = {"v": 0}
    wlock = threading.Lock()
    produced = {"n": 0, "dropped": 0}
    t0 = time.monotonic()

    # ---------------- producer: keep the inference GPUs busy ----------------
    def producer():
        cursor = 0
        while not stop.is_set():
            batch_probs = [problems[(cursor + i) % len(problems)]
                           for i in range(cfg.prompts_per_step)]
            cursor += cfg.prompts_per_step
            prompts = [build_chat(tok, p) for p in batch_probs]
            with wlock:
                v_at_start = weight_version["v"]
            try:
                outs = gen.generate(prompts, n=cfg.group_size, lag=v_at_start)
            except Exception as e:                       # engine died — surface, don't hang
                tel.emit("error", where="producer", err=f"{type(e).__name__}: {e}")
                stop.set()
                break
            with wlock:
                v_now = weight_version["v"]
            # Lag measured at completion: how many optimizer steps landed while these
            # sequences were being generated.
            lag = max(0, v_now - v_at_start)
            rolls = vllm_output_to_rollouts(outs, batch_probs, reward_fn,
                                            lag=lag, tokenizer=tok)
            produced["n"] += len(rolls)
            for r in rolls:
                tel.sample(reward=r.reward, tokens=len(r.completion_ids),
                           lag=r.lag, prompt_id=r.pid)
            try:
                rollout_q.put(rolls, timeout=30)
            except queue.Full:
                produced["dropped"] += len(rolls)
                tel.emit("backpressure", dropped=len(rolls))

    th = threading.Thread(target=producer, daemon=True)
    th.start()

    # ---------------- consumer: train + publish weights ---------------------
    step = 0
    consumed = 0
    stale_dropped = 0
    history = []

    while True:
        elapsed = time.monotonic() - t0
        if cfg.budget == "wallclock" and elapsed >= cfg.wallclock_s:
            break
        if cfg.budget == "samples" and consumed >= cfg.max_samples:
            break
        if step >= cfg.max_steps or stop.is_set():
            break

        # Mark trainers as waiting (not idle) when the queue is empty — the distinction
        # matters: waiting means work exists elsewhere, idle means nothing is happening.
        for g in train_gpus:
            tel.gpu(g, "train", "waiting")
        try:
            rolls = rollout_q.get(timeout=60)
        except queue.Empty:
            tel.emit("starved", step=step)
            continue

        with wlock:
            v_now = weight_version["v"]
        fresh = [r for r in rolls if (v_now - r.lag) <= cfg.max_lag]
        # NOTE: rollouts arrive already grouped; filtering must not break group alignment,
        # so we drop whole groups rather than individual members.
        if len(fresh) != len(rolls):
            stale_dropped += len(rolls) - len(fresh)
        keep = len(rolls) - (len(rolls) % cfg.group_size)
        rolls = rolls[:keep]
        if not rolls:
            continue

        batch, info = rollouts_to_batch(rolls, tok, cfg.group_size, trainer.dev)
        stats = trainer.step(batch)
        consumed += len(rolls)
        step += 1

        # ---- publish weights INTO THE LIVE ENGINE ----
        # Fatal on failure, deliberately. A collective_rpc exception poisons the vLLM
        # executor, so continuing would mean the generator serves stale weights forever
        # while the trainer keeps stepping and the reward curve keeps moving — a run that
        # looks healthy and means nothing. Better to stop with the partial stream on disk.
        try:
            # inflight is what the ENGINE actually did, never what the config asked for.
            # With the synchronous LLM API the engine lock forces the push to wait for the
            # in-progress generate() to return, so the update lands between batches.
            gen.push_weights(trainer.inference_weights(), step=step, src_gpus=train_gpus,
                             inflight=cfg.inflight_updates and gen.supports_inflight)
        except EngineWeightError as e:
            tel.emit("fatal", where="push_weights", step=step, err=str(e))
            print(f"[pipeline] FATAL at step {step}: {e}", flush=True)
            stop.set()
            break
        with wlock:
            weight_version["v"] = step

        history.append({"step": step, "t": round(time.monotonic() - t0, 2),
                        "samples": consumed, "stale_dropped": stale_dropped,
                        **info, **stats})
        if step % 10 == 0:
            tel.checkpoint()   # survive a hard abort with a usable partial stream

    stop.set()
    th.join(timeout=120)
    return {"arm": "pipeline", "steps": step, "samples": consumed,
            "produced": produced["n"], "backpressure_dropped": produced["dropped"],
            "stale_dropped": stale_dropped,
            "wallclock_s": round(time.monotonic() - t0, 2), "history": history}
